---
title: ""
output: pdf_document
classoption: landscape
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magick)
library(webshot)
library(knitr)
library(kableExtra)
library(tidyverse)
library(readxl)
```
# SLR Typology
## Frequency of Use
```{r, include=TRUE, echo=FALSE}

# define data directory
datadir <- file.path('/Users/dhardy/Dropbox/r_data/sea-level-rise')

# create data table
dat <- read_excel(file.path(datadir, 'data/slr-typology-litreview.xlsx'), sheet = 'Analysis') %>%
  slice(1:n()-1)

df <- dat %>%
  summarise_at(vars(MSL:Storms), sum, na.rm = TRUE)
  
# LaTeX Table
kable(df, format = "latex", booktabs = T, caption = NULL) %>%
  kable_styling(latex_options = "scale_down",
                full_width = NULL) %>%
  # add_header_above(c(" ", "Private" = 2, "Public" = 2)) %>%
  # add_footnote(c("table footnote")) %>%
  as_image(width = 9)
```

## Papers
```{r, include=TRUE, echo=FALSE}

# define data directory
datadir <- file.path('/Users/dhardy/Dropbox/r_data/sea-level-rise')

# create data table
dat <- read_excel(file.path(datadir, 'data/slr-typology-litreview.xlsx'), sheet = 'Analysis') %>%
  slice(1:n()-1)

df <- dat %>%
  mutate(AuthorYear = str_c(AUTHORS_ETAL, ' (', YEAR, ')', sep = '')) %>%
  select(AuthorYear, `AVG CITES/YEAR`, MSL:Storms) %>%
  replace(is.na(.), "")

coln <- df %>%
  colnames()
#  c('Source', 'Average Cites/Year')

# LaTeX Table
kable(df, format = "latex", booktabs = T, caption = NULL,
      col.names = coln) %>%
  kable_styling(latex_options = c("stripe", "scale_down"),
                full_width = NULL) %>%
  # add_header_above(c(" ", "Private" = 2, "Public" = 2)) %>%
  # add_footnote(c("table footnote")) %>%
  as_image(width = 9)
```
